# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pootle_store', '0028_set_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_revision', models.IntegerField(blank=True, db_index=True, default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clone', to='pootle_store.Unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_unit', to='pootle_store.Unit')),
            ],
        ),
    ]
